apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  labels:
    application: f5dcs-logReceiverProxy
    component: redis-server
    type: single
spec:
  replicas: 1
  selector:
    matchLabels:
      application: f5dcs-logReceiverProxy
      component: redis-server
      type: single
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: f5dcs-logReceiverProxy
        component: redis-server
        type: single
    spec:
      containers:
        - image: redis
          name: redis-server
          ports:
            - containerPort: 6379
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    application: f5dcs-logReceiverProxy
    component: redis-server
    type: single
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    application: f5dcs-logReceiverProxy
    component: redis-server
    type: single
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: f5dcs-logReceiverProxy
    component: receiverservice
  name: receiverservice
spec:
  replicas: 1
  selector:
    matchLabels:
      application: f5dcs-logReceiverProxy
      component: receiverservice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: f5dcs-logReceiverProxy
        component: receiverservice
        redeploy: '1'
    spec:
      containers:
        - name: receiverservice
          image: gregorycoward/f5dcs-logreceiver:1.1
          env:
          - name: REDIS_SERVER_IP
            value: "redis-server"
          ports:
          - name: receiverservice
            containerPort: 601
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: receiverservice
  labels:
    application: f5dcs-logReceiverProxy
    component: receiverservice
spec:
  type: NodePort
  selector:
    application: f5dcs-logReceiverProxy
    component: receiverservice
  ports:
  - protocol: TCP
    port: 601
    targetPort: 601