# version of docker-compose
version: '3.3'
# 'services' are equivalent to 'containers'
services:
  redis-server:
    # Use Docker Hub base image 'redis' 
    image: 'redis'
  receiver-service:
    restart: on-failure
    image: 'gregorycoward/f5dcs-logreceiver:1.1.0'
    # Specify an array of ports to map
    environment:
      - LISTEN_PORT=30601
    ports:
      - '30601:30601'
  publisher-service:
    restart: on-failure
    image: 'gregorycoward/f5dcs-logpublisher:1.1.0'
    environment:
      - SPLUNK_HOST=206.124.129.189
      - SPLUNK_HEC=ba5dce62-0254-474d-80b5-b25b30198ecb
      - DATADOG_TOKEN=a1354e93ef308fa95daac9c63628eec6
      - ANALYTIC_PROVIDER=splunk    # - Enter either 'splunk' or 'datadog'
