# version of docker-compose
version: '3.3'
# 'services' are equivalent to 'containers'
services:
  redis-server:
    # Use Docker Hub base image 'redis' 
    image: 'gregorycoward/redis:1.0.0'
  receiver-service:
    restart: on-failure
    image: 'gregorycoward/f5dcs-logreceiver:1.1.0'
    # Specify an array of ports to map
    environment:
      - LISTEN_PORT=30601
    ports:
      - '30601:30601'
  publisher-service:
    restart: on-failure
    image: 'gregorycoward/f5dcs-logpublisher:1.1.0'
    environment:
      - SPLUNK_HOST=xxxxxxxxxxxx
      - SPLUNK_HEC=txxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - DATADOG_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - ANALYTIC_PROVIDER=splunk    # - Enter either 'splunk' or 'datadog'
