apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
spec:
  selector:
    matchLabels:
      run: redis-server
  replicas: 1
  template:
    metadata:
      labels:
        run: redis-server
    spec:
      containers:
      - name: redis-server
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  labels:
    run: redis-server
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    run: redis-server
